POST http://localhost:1236/movie
Content-Type: application/json

{
  "id": null,
  "name": "jodaee nader az simin ",
  "year": 1400,
  "description": "chos nale",
  "duration": 120,
  "directorDTO": [
    {
      "id": null,
      "name": "asgahr farhadi",
      "yearOfBirth": 1340,
      "gender": "male",
      "country": "iran",
      "movieDTO": null
    },
    {
      "id": null,
      "name": "kianian",
      "yearOfBirth": 1340,
      "gender": "male",
      "country": "iran",
      "movieDTO": null
    }
  ]
}


###
GET http://localhost:1236/movie

###
GET http://localhost:1236/movie/1

###
DELETE http://localhost:1236/movie/1
